services:
  puppetserver:
    container_name: puppetserver
    hostname: puppet
    image: voxpupuli/puppetserver
    environment:
      PUPPETSERVER_ENVIRONMENT_TIMEOUT: 0
    ports:
      - 8140:8140
    volumes:
      - ./modules:/etc/puppetlabs/code/modules
      - ./manifests:/etc/puppetlabs/code/environments/production/manifests
      - ./Puppetfile:/etc/puppetlabs/code/environments/production/Puppetfile
      - ./ca-ssl:/etc/puppetlabs/puppetserver/ca
      - ./auth.conf:/etc/puppetlabs/puppetserver/conf.d/auth.conf
