version: '3'

services:
  puppet:
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - 8140:8140
    volumes:
      - ./manifests:/etc/puppetlabs/code/environments/production/manifests
      - ./functions:/etc/puppetlabs/code/environments/production/lib/puppet/functions
      - ./facter:/etc/puppetlabs/code/environments/production/modules/facts/lib/facter
      - ./Puppetfile:/etc/puppetlabs/code/environments/production/Puppetfile